version: '3'

services:
  scylla:
    image: scylladb/scylla
    container_name: video_streaming_db
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    command: --smp 1 
    environment:
      - SCYLLA_DEVELOPER_MODE=1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  scylla_data: